import type { Metadata } from "next";
import Link from "next/link";
import { BRAND } from "@/lib/config";
import { LegalPage, LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${BRAND.name} collects, uses, and protects the information you share when you search for home buyer grants.`,
  alternates: { canonical: `${BRAND.siteUrl}/privacy` },
};

export default function PrivacyPage() {
  const contact = (
    <a href={`mailto:${BRAND.realtor.email}`} className="underline underline-offset-4">
      {BRAND.realtor.email}
    </a>
  );
  return (
    <LegalPage
      eyebrow="Privacy"
      title="Privacy Policy"
      intro={`${BRAND.name} is a free grant-matching service for home buyers. This policy explains what we collect, why, and the choices you have.`}
    >
      <LegalSection title="Who we are">
        <p>
          {BRAND.name} is operated by {BRAND.realtor.name}, a licensed real estate
          salesperson in {BRAND.realtor.licenseState} (License #{BRAND.realtor.licenseNumber})
          with {BRAND.realtor.brokerage}. Questions about this policy can be sent to {contact}.
        </p>
      </LegalSection>

      <LegalSection title="What we collect">
        <p>
          <strong>Buyer profile.</strong> The answers you give in the grant finder: the state,
          city, or county where you want to buy, household size, household income, target
          purchase price, approximate credit score, first-time buyer status, military status,
          profession, and whether you plan to live in the home. We use this only to match you
          against program eligibility rules.
        </p>
        <p>
          <strong>Contact details.</strong> Your name, email address, and phone number when
          you choose to save your matches, request help applying for a program, or sign up for
          program updates. We also record which programs you matched or asked about.
        </p>
        <p>
          <strong>Technical data.</strong> Standard server logs (IP address, browser type,
          pages visited, timestamps) generated by our hosting provider to keep the site
          running and secure. We do not use advertising trackers or sell behavioral data.
        </p>
        <p>
          We never ask for, and you should never send us, your Social Security number, bank
          account numbers, or full credit report. We do not pull your credit.
        </p>
      </LegalSection>

      <LegalSection title="How we use it">
        <ul className="list-disc space-y-2 pl-6">
          <li>To match you with federal, state, county, and city home buyer programs.</li>
          <li>
            To contact you by email, phone, or text message about the programs you matched,
            to help you apply, and to answer your questions. You can ask us to stop at any time.
          </li>
          <li>To send program updates and a weekly digest if you asked for one.</li>
          <li>To improve the accuracy of our program database and the matching service.</li>
          <li>To comply with legal obligations and enforce our Terms of Service.</li>
        </ul>
      </LegalSection>

      <LegalSection title="Who we share it with">
        <p>
          <strong>Your grant specialist.</strong> When you ask for help applying, your contact
          details and matched programs are shared with {BRAND.realtor.name} and{" "}
          {BRAND.realtor.brokerage} so they can reach out and assist you. Where a program
          requires working with a participating lender or housing counselor, we will tell you
          before introducing you.
        </p>
        <p>
          <strong>Service providers.</strong> We use third-party vendors for website hosting,
          database storage, and email delivery. They process data on our behalf and are not
          permitted to use it for their own purposes.
        </p>
        <p>
          <strong>Legal reasons.</strong> We may disclose information if required by law, to
          protect our rights, or to protect the safety of any person.
        </p>
        <p>
          <strong>We do not sell your personal information</strong>, and we do not share it with
          data brokers or advertisers.
        </p>
      </LegalSection>

      <LegalSection title="Text messages and calls">
        <p>
          By providing your phone number and continuing, you agree that we may call or text you
          at that number about your grant matches and application, including with automated
          dialing or messaging technology. Consent is not a condition of purchase. Message and
          data rates may apply. Reply STOP to any text to opt out, or email {contact}.
        </p>
      </LegalSection>

      <LegalSection title="How long we keep it">
        <p>
          We keep your buyer profile and contact details for as long as needed to help you with
          your home purchase and for a reasonable period afterward for record keeping, unless you
          ask us to delete them sooner.
        </p>
      </LegalSection>

      <LegalSection title="Your choices">
        <ul className="list-disc space-y-2 pl-6">
          <li>You can use the grant finder without giving us your name or contact details.</li>
          <li>You can unsubscribe from emails using the link in any message.</li>
          <li>You can reply STOP to any text message to stop receiving texts.</li>
          <li>
            You can ask us to correct, export, or delete the information we hold about you by
            emailing {contact}. We will respond within 30 days.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="Security">
        <p>
          We use industry-standard safeguards, including encrypted connections (HTTPS) and
          access controls, to protect your information. No method of transmission or storage is
          completely secure, so we cannot guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection title="Children">
        <p>
          {BRAND.name} is intended for adults. We do not knowingly collect information from
          anyone under 18. If you believe a minor has provided us information, contact us and
          we will delete it.
        </p>
      </LegalSection>

      <LegalSection title="Changes to this policy">
        <p>
          We may update this policy from time to time. The date at the top shows when it was
          last revised. Material changes will be posted on this page before they take effect.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Email {contact}. See also our{" "}
          <Link href="/terms" className="underline underline-offset-4">
            Terms of Service
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
